### ISSUE TITLE
Largest remainder methods: Half votes rounded down, party receiving less seats

### ISSUE THREAD

**Issue by anonymous7002** [julien-boudry/Condorcet#112]
| Q                   | A
| --------------------| ---------------
| Type                | Bug
| Condorcet version   | 4.2.0
| PHP version         | 8.1.12
| Installation Method | Composer

If a party receives 23.5/48 of the votes, and there are 200 seats, the party should receive at least 97 of the seats.
Using d'Hondt and Sainte-Laguë methods, the party in my dataset received 99 seats, but under Hare-LR, it only received 96, as if it had only got 23/48 of the votes.
By running method-stats, the number of votes allocated is shown to be rounded down to the nearest integer 23 in all the PR methods, but the highest averages methods seem to be executed with 23.5 votes, but the largest remainder methods don't.

**Comment by julien-boudry** [comment]
HI @anonymous7002 
If you have the ability to produce a test data set with the expected results and stats. It can help.

On the substance of the concern, I will look into it as soon as I have some brain time available to dive back into the intricacies of this method, probably after the weekend :-/

Thanks for the report.

**Comment by julien-boudry** [comment]
@anonymous7002 What do you mean about 23.5 votes / 48? Condorcet don't support decimal in vote weight.

If I try something like: `A*23;B*20;C*5` => 96 seats for A.
If I transfert one more vote to A: `A*24;B*20;C*4`=> 100 seats for A
Now, If a emulate an half by double the vote: `A*47;B*40;C*9` => 98 seats for A

**Comment by anonymous7002** [comment]
23.5 votes / 48 means that out of the 48 votes, 23 voted A, and one voted both A and some other candidate as their first choice, hence the vote is split between the two.

**Comment by julien-boudry** [comment]
Let's see with this one:
```shell
bin/condorcet Election -c "A;B;C" -w "A*23;B*20;C*4;C=A" --seats 200 --stats LR
```

```shell
+---------------------------------------------------------------------------+
| 'Seats per Candidates':                                                   |
|     A: 97                                                                 |
|     B: 85                                                                 |
|     C: 18    
```

Look good for me.
