### ISSUE TITLE
Different results when running different numbers of methods

### ISSUE THREAD

**Issue by LiamM32** [julien-boudry/Condorcet#155]
Just to test that the program works as it should for the Schulze Method, I tested the set of votes in the [Wikipedia example](https://en.wikipedia.org/wiki/Schulze_method#Example).

I discovered some strange behaviour. Sometimes _A_ wins, sometimes _E_ wins with the Schulze method.

I found that if I run the program interactively, and run the votes through many different methods, then _E_ is the winner of both Schulze methods. If I only run it through _Schulze Winning_ & _Schulze Margins_, then _A_ is the winner of both Schulze methods. If I use a .cvotes file, then A is the winner.
[output1.txt](https://github.com/julien-boudry/Condorcet/files/11853752/output1.txt)
[output2.txt](https://github.com/julien-boudry/Condorcet/files/11853753/output2.txt)
[output3.txt](https://github.com/julien-boudry/Condorcet/files/11853758/output3.txt)

It wouldn't let me upload the .cvotes file, so here it is:
```
#From Wikipedia Example: https://en.wikipedia.org/wiki/Schulze_method#Example
#/Candidates: A; B; C; D; E
#/Implicit Ranking: true
#/Weight allowed: false

#Here are the votes:
A > C > B > E > D *5
A > D > E > C > B *5
B > E > D > C > B *8
C > A > B > E > D *3
C > A > E > B > D *7
C > B > A > D > E *2
D > C > E > B > A *7
E > B > A > D > C *8

```

**Comment by julien-boudry** [comment]
There is an error in your inputs.

Output 2 and 3 are equal and give the same result.
But output 1 has a typo on vote line N°3, it is invalid. So the result is different, and it's normal.

Can you confirm that can I close this issue as no a bug? ;-)

**Comment by julien-boudry** [comment]
If it's confusing, a project could be to migrate for permissive philosophy with silent error (can have som advantage) to a more strict error intolerant inputs.

**Comment by LiamM32** [comment]
I don't think the program should stop without results when this happens, but there should be warning messages for invalid votes, and it should display a limited number of invalid votes in the output. There should also be a function in the public API to verify that a vote is valid, if there isn't already.

**Comment by LiamM32** [comment]
Yes this turned out to be the case. Thank you as I could not find what was the difference between the two sets of votes. When corrected, _E_ is the winner, as the Wikipedia example says should happen.
