### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by janmotl** [julien-boudry/Condorcet#20]
The result page on https://www.condorcet.vote possibly contains typos:

1. Optionnal -> Optional
2. personnal -> personal
3. This URL can be use by anyone to vote -> This URL can be used by anyone to vote
4. Schulze (Winning variant, recommand by M.Schulze itself) . -> Schulze (Winning variant, recommended by M. Schulze himself).
5. Vote tag or number separated by semicolon. -> Vote tags or numbers separated by semicolons.

**Comment by julien-boudry** [comment]
Thanks. Will be push in prod soon, maybe with #19 ?

For the following , please post it on [julien-boudry/Condorcet.Vote ](https://github.com/julien-boudry/Condorcet.Vote). I try to provide this online service with minimal maintenance.
