### ISSUE TITLE
Zip download is missing most of the folders

### ISSUE THREAD

**Issue by Shdwdrgn** [julien-boudry/Condorcet#22]
| Q                   | A
| --------------------| ---------------
| Type                | Bug
| Concorcet version   | 1.6.0
| PHP version         | N/A
| Installation Method | N/A

I just downloaded the current zip file and the only folder included it "lib".  All other folders including "Examples" appear to be missing from the zip.

**Comment by julien-boudry** [comment]
Yes, it is curious.
The. gitattributes file determines files that are useless in a production environment, and even dangerous (tests, examples). Only during a git deployment with the corresponding options.

Curiously, Github himself seems to consider this file when producing a zip. which is quite unexpected behavior!
I don't really have a solution, I advise you to go through the normal way => git clone

If you didn't know how to... just tell me and I'll send you a home zip.

**Comment by Shdwdrgn** [comment]
I was just grabbing the files manually.  I thought github grabbed all the files within a project to create their zips, this is the first time I've seen anything missing.  Very curious indeed!  I just thought I would bring it up since I hadn't seen any other bug reports of the issue.

**Comment by julien-boudry** [comment]
Let me know if you have any question about Condorcet.  I'm always curious to know the use cases.

**Comment by Shdwdrgn** [comment]
Well I was hoping to test it for handling some department votes, however it looks like the examples were written to only work on PHP7 and we are still using PHP5 here.  Do you happen to have any examples that would work on older versions?

**Comment by julien-boudry** [comment]
You can try oldstable version 1.0 : https://github.com/julien-boudry/Condorcet/tree/VERSION/1.0.x
It's working with PHP 5.6.

However, the world is at PHP 7.2. I suggest a migration !
