### ISSUE TITLE
What is the syntax of command line candidates+votes file?

### ISSUE THREAD

**Issue by anonymous7002** [julien-boudry/Condorcet#29]

**Comment by julien-boudry** [comment]
Hi,
Sorry for the delay.
You can found syntax on Wiki: 
- https://github.com/julien-boudry/Condorcet/wiki/II-%23-A.-Create-an-Election-%23-2.-Create-Candidates
- https://github.com/julien-boudry/Condorcet/wiki/II-%23-B.-Vote-management-%23-1.-Add-Vote
