### ISSUE TITLE
condorcet.vote is unfinished

### ISSUE THREAD

**Issue by anonymous7002** [julien-boudry/Condorcet#34]
I think condorcet.vote is quite unfinished. You're only allowed to enter alphanumeric characters, and the translation is horrible.

**Comment by julien-boudry** [comment]
Hi @anonymous7002,

Condorcet.Vote is an another project, you can found it here: https://github.com/julien-boudry/Condorcet.Vote

And he is no longer maintained for now (he was never finished). But you can create a pull request for translation.
