### ISSUE TITLE
Add Vote method: Ranking from a simple string

### ISSUE THREAD

**Issue by phplicengine** [julien-boudry/Condorcet#35]
| Q                   | A
| --------------------| ---------------
| Type                |  Support 
| Concorcet version   |3
| PHP version         |7.4
| Installation Method | Composer

I need clarification about below. For example if candidate1 gets 1 from a voter and gets 2 from another voter, how should I use `>` among them? How do I know if this is A > B or B >A?

```php
  // Add some votes, by some ways
  $myElection1->addVote(  [
                              $candidate2, // 1
                              [$candidate1, $candidate4] // 2 - Tie
                              // Last rank is optionnal. By default, it will be implicitly completed in $candidate3. This behaviour can be changed by election, before, during or after the vote. The initial submission being preserved.
                          ]
  );

  $myElection1->addVote('Candidate 2 > Candidate 3 > Candidate 4 = Candidate 1'); // Last rank can also be omitted

  $myElection1->parseVotes(
              'Candidate 1 > Candidate 2 = Candidate 4 > Candidate 3 * 4
              Candidate 3 > Candidate 1 * 3'
  );
```

**Comment by julien-boudry** [comment]
Hi @phplicengine 

I'm sorry, but I don't quite understand your question. 
Can you give me a more specific example of a vote that you think is ambiguous in its interpretation? Whatever the method of entry.

**Comment by phplicengine** [comment]
Hi @julien-boudry 

I meant what does `>` and `=` mean? Do they mean to show priority of voter? For example A > B=C > D means A has highest priority and B and C both have second position for voter and D has the least position/priority for voter?

**Comment by julien-boudry** [comment]
Ok, Let's look at this example:

```php
    $vote = new  Vote('Candidate 5 > Candidate 3 > Candidate 4 = Candidate 1 > Candidate2');

    var_dump( CondorcetUtil::format( $vote->getRanking() ) );
```

```
array(4) {
  [1]=>
  string(11) "Candidate 5"
  [2]=>
  string(11) "Candidate 3"
  [3]=>
  array(2) {
    [0]=>
    string(11) "Candidate 4"
    [1]=>
    string(11) "Candidate 1"
  }
  [4]=>
  string(10) "Candidate2"
}
```

The array key are the rank in the context of this vote. Candidate5 is the first, then: Candidate3.
Candidate4 & 1 are equals on in third place.
Then Candidate2 at last

**Comment by julien-boudry** [comment]
If you are not comfortable, you can also put an array as input, instead of this string.

**Comment by phplicengine** [comment]
This is not directly related to your script but I hope to get your help how to create a php script to create votes.

Consider I have 5 items: A, B, C, D, E
I want my user create priority position among them e.g. via a drop down list or whatever. For example here is a priority list for a user: A > B = C > D > E

How can I sort these items based on their priority to get the output above?
I mean how to set their priority and give such output?

**Comment by julien-boudry** [comment]
Hi,

For input, you can prefer to use an array, or a JSON (look Election->addVotesFromJson method).

Then, you can do a `$vote->getSimpleRanking()`  to get the string like `A > B = C > D > E`
https://github.com/julien-boudry/Condorcet/blob/master/Documentation/Vote%20Class/public%20Vote--getSimpleRanking.md

For the result, same thing :
`$result->getResultAsString()`

**Comment by phplicengine** [comment]
Hi,

Thanks a lot. I am grateful if you help to create a user form to output a valid array structure in order to use `getSimpleRanking()`.

Thanks,

**Comment by phplicengine** [comment]
I still have problem how to get a valid array structure for Condorcet via a form as form array structure has a different structure. if you help with this then I am just fine.

@julien-boudry

**Comment by julien-boudry** [comment]
It's your role to get the correct array structure OR the correct string structure (ex: `B > A = D > C`). Before passing them into Condorcet.

PHP Array or Json have a very close structure, so you can easily simply do a decode/encode json if needed.

The input formats documentation is here :
https://github.com/julien-boudry/Condorcet/wiki/II-%23-B.-Vote-management-%23-1.-Add-Vote

**Comment by phplicengine** [comment]
I was thinking of this way:

<select name="item[]"> on all items.

This will POST the selected items in an array.
```php
$_POST["item"][0] will be the highest priority
$_POST["item"][1] the second
$_POST["item"][2] the third, and so on
```
But the problem of this html code for dropdown menu is that what if the most bottom item in menu has a higher rank in the opinion of user than the item above that. Any better idea than using drop down menu to solve the problem? 

I am stuck, Please help.
@julien-boudry

**Comment by julien-boudry** [comment]
It is difficult to interpret your case correctly.
The input table will be reordered by Condorcet, classified by its keys. So if the input table is disordered or the keys are a bit fancy (presence of a0, large numbers, holes between rows), it's not a problem because Condorcet will clean it up without worrying. You must, of course, make sure that the vote is the right one.

For example:

```php
[
   42 => 'A',
   0 => 'B',
   3 => 'C',
   1 => 'D'
]
```

Condorcet will interpret it as : 
```php
[
   1 => 'B',
   2 => 'D',
   3 => 'C',
   4 => 'A'
]
```
