### ISSUE TITLE
change of pdo_sqlite to pdo_mysql

### ISSUE THREAD

**Issue by phplicengine** [julien-boudry/Condorcet#36]
| Q                   | A
| --------------------| ---------------
| Type                | Bug / Support
| Concorcet version   | 2.x.x
| PHP version         | 7.4
| Installation Method | __CondorcetAutoload.php

I changed this

```php
$pdo_object = new \PDO ('sqlite:'.__DIR__.'/bdd.sqlite');
```
to this:
```php
    $pdo_object = new \PDO('mysql:host=127.0.0.1;dbname=dbtest', 'dbuser', 'dbpass');
```
and I got below. What should I do?

[26-Apr-2021 07:53:34 America/Chicago] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AUTO_INCREMENT INTEGER PRIMARY KEY NOT NULL , data BLOB NOT NULL )' at line 1 in vendor/julien-boudry/condorcet/lib/DataManager/DataHandlerDrivers/PdoDriver/PdoHandlerDriver.php:70
Stack trace:
#0 vendor/julien-boudry/condorcet/lib/DataManager/DataHandlerDrivers/PdoDriver/PdoHandlerDriver.php(70): PDO->exec('CREATE TABLE IF...')
#1 vendor/julien-boudry/condorcet/lib/DataManager/DataHandlerDrivers/PdoDriver/PdoHandlerDriver.php(48): CondorcetPHP\Condorcet\DataManager\DataHandlerDrivers\PdoDriver\PdoHandlerDriver->createTable()
#2 vendor/julien-boudry/condorcet/Examples/Specifics_Examples/use_large_election_external_database_drivers.php(44): CondorcetPHP\Condo in vendor/julien-boudry/condorcet/lib/DataManager/DataHandlerDrivers/PdoDriver/PdoHandlerDriver.php on line 70

EDIT:
The query '...AUTO_INCREMENT INTEGER PRIMARY KEY NOT NULL , data BLOB
NOT NULL...' doesn't seem to be valid on MySQL.

You mentioned "We will use PDO SQLITE, but can
be MySQL or else" but it doesn't seem to be true if the project uses
queries that are not supported.

**Comment by julien-boudry** [comment]
Look like a real bug. I will fix it for 3.x branch. I probably backport it for 2.x

Are you sure to need the MySQL integration? You will work with large dataset.
In fact, the MySQL version has never really been tested. You are experiencing the most experimental functionality, but don't worry.

**Comment by julien-boudry** [comment]
A quick fix can be to create the table structure yourself. Just remove the table creation.
`new PdoHandlerDriver ($pdo_object, FALSE, $database_map);`

**Comment by julien-boudry** [comment]
Hi @phplicengine 

I just commit on both branch :
3.x : 720a44bf96622ba9cfb8aa56f6d1fac8f63ce4c8  
For 2.2 branch : 25f573949aad1b2d6b75cb726e9ea8db1685628e 

Can you try it, and tell me if it's working for you?
Thanks,

**Comment by julien-boudry** [comment]
Hi @phplicengine : Any news about that ?

Thanks
