### ISSUE TITLE
Is it possible to use ranking for a single candidate?

### ISSUE THREAD

**Issue by phplicengine** [julien-boudry/Condorcet#40]
| Q                   | A
| --------------------| ---------------
| Type                | Support
| Concorcet version   | 2.2.3
| PHP version         | 7.4
| Installation Method | __CondorcetAutoload.php

Imagine we have only one candidate and users vote for it from 1= worst to 5 = the best. Then how to use Condorcet? I used below but it seems I am wrong, please advise.

```php
    $election->addCandidate(new Candidate ('Candidate1'));
    $json_votes = json_encode([
	['vote' => '1'], // A user voted 1 as the worst.
	['vote' => '2'],
	['vote' => '3']]); // Another user voted 5 as the best.
   $vote = new Vote('Candidate1');
   $ranking = $vote->setRanking ($json_votes);
```

**Comment by julien-boudry** [comment]
Oulà!

It's completly out of scope. It's not a Condorcet method or anything else managed by CondorcetPHP.
Maybe you can emulate it with many candidates: Note1, Note2, Note3, Note4, Note5 and let the user vote.

See the documentation for Json input, you wrong to.
https://github.com/julien-boudry/Condorcet/wiki/II-%23-B.-Vote-management-%23-1.-Add-Vote#add-multiple-votes-from-json
