### ISSUE TITLE
simple explanation

### ISSUE THREAD

**Issue by phplicengine** [julien-boudry/Condorcet#44]
| Q                   | A
| --------------------| ---------------
| Type                | Support
| Concorcet version   | 2.x
| PHP version         | 7.4
| Installation Method | Composer

Please give simple explanation what are `weight` and `tag` and what are their purposes?

**Comment by julien-boudry** [comment]
- https://github.com/julien-boudry/Condorcet/wiki/II-%23-C.-Result-%23-4.-Vote-weight
- https://github.com/julien-boudry/Condorcet/wiki/II-%23-B.-Vote-management-%23-2.-Manage-Vote
