### ISSUE TITLE
How do you output election results as a file when using the command line?

### ISSUE THREAD

**Issue by ragland-t** [julien-boudry/Condorcet#50]
| Q                   | A
| --------------------| ---------------
| Type                | Support
| Condorcet version   | 3.0.2
| PHP version         | n/a
| Installation Method | Docker container public image

When running a simple election command from the command line, is there a way to output the results as a file? I would like to output a simple CSV with `rank,candidate` headers. Is this possible?

**Comment by julien-boudry** [comment]
Hi @ragland-t,

Actually, it's not natively possible. If you run the Docker and not using the interactive mode (put all input directly), you can easily use the operator **>**

For example:
`docker run --hostname=condorcet -it --rm julienboudry/condorcet election -c "A;B;C" -w "A>B;A>C;C>B" -r > result.txt`

It's working on bash and also on windows.
